name: 'Check'

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
      - run: bun install
      - name: Check lint
        run: npm run lint
      - name: Check formatting
        run: npm run format:check
