name: 'Test'

on:
  push:
    branches:
      - 'main'
    pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
      - run: bun install
      - run: npm run test
